import type { LocalAppDefinition } from "./types";

export const APP_REGISTRY: readonly LocalAppDefinition[] = [
  {
    id: "vscode",
    name: "VS Code",
    kind: "editor",
    icon: "vscode",
    supportedFileKinds: ["text"],
    windows: {
      executables: ["Code.exe", "code.cmd"],
      appPaths: ["Code.exe"],
      uninstallNames: ["Microsoft Visual Studio Code"],
      knownPaths: [
        "%LOCALAPPDATA%\\Programs\\Microsoft VS Code\\Code.exe",
        "%ProgramFiles%\\Microsoft VS Code\\Code.exe",
      ],
    },
    macos: {
      bundleIds: ["com.microsoft.VSCode"],
      appNames: ["Visual Studio Code"],
    },
    linux: {
      executables: ["code"],
      desktopIds: ["code.desktop", "com.visualstudio.code.desktop"],
      flatpakIds: ["com.visualstudio.code"],
    },
  },
  {
    id: "cursor",
    name: "Cursor",
    kind: "editor",
    icon: "cursor",
    supportedFileKinds: ["text"],
    windows: {
      executables: ["Cursor.exe", "cursor.cmd"],
      appPaths: ["Cursor.exe"],
      uninstallNames: ["Cursor"],
      knownPaths: ["%LOCALAPPDATA%\\Programs\\cursor\\Cursor.exe"],
    },
    macos: {
      bundleIds: ["com.todesktop.230313mzl4w4u92"],
      appNames: ["Cursor"],
    },
    linux: {
      executables: ["cursor"],
      desktopIds: ["cursor.desktop", "Cursor.desktop"],
    },
  },
  {
    id: "trae",
    name: "Trae",
    kind: "editor",
    icon: "trae",
    supportedFileKinds: ["text"],
    windows: {
      executables: ["Trae.exe", "trae.exe", "trae.cmd"],
      appPaths: ["Trae.exe"],
      uninstallNames: ["Trae"],
      uninstallNameExcludes: ["Trae CN"],
      knownPaths: ["%LOCALAPPDATA%\\Programs\\Trae\\Trae.exe", "%ProgramFiles%\\Trae\\Trae.exe"],
    },
    macos: {
      bundleIds: ["com.trae.app"],
      appNames: ["Trae"],
    },
    linux: {
      executables: ["trae"],
      desktopIds: ["trae.desktop"],
    },
  },
  {
    id: "trae-cn",
    name: "Trae CN",
    kind: "editor",
    icon: "trae",
    supportedFileKinds: ["text"],
    windows: {
      executables: ["Trae CN.exe", "trae-cn.exe", "trae-cn.cmd"],
      appPaths: ["Trae CN.exe"],
      uninstallNames: ["Trae CN"],
      knownPaths: [
        "%LOCALAPPDATA%\\Programs\\Trae CN\\Trae CN.exe",
        "%ProgramFiles%\\Trae CN\\Trae CN.exe",
      ],
    },
    macos: {
      bundleIds: ["cn.trae.app"],
      appNames: ["Trae CN"],
    },
    linux: {
      executables: ["trae-cn"],
      desktopIds: ["trae-cn.desktop"],
    },
  },
  {
    id: "qoder",
    name: "Qoder",
    kind: "editor",
    icon: "qoder",
    supportedFileKinds: ["text"],
    windows: {
      executables: ["Qoder.exe", "qoder.exe", "qoder.cmd"],
      appPaths: ["Qoder.exe"],
      uninstallNames: ["Qoder"],
      knownPaths: [
        "%LOCALAPPDATA%\\Programs\\Qoder\\Qoder.exe",
        "%ProgramFiles%\\Qoder\\Qoder.exe",
      ],
    },
    macos: {
      bundleIds: ["com.qoder.ide"],
      appNames: ["Qoder"],
    },
    linux: {
      executables: ["qoder"],
      desktopIds: ["qoder.desktop"],
    },
  },
  {
    id: "idea",
    name: "IntelliJ IDEA",
    kind: "editor",
    icon: "idea",
    supportedFileKinds: ["text"],
    windows: {
      executables: ["idea64.exe", "idea.exe"],
      uninstallNames: ["IntelliJ IDEA"],
      toolbox: true,
    },
    macos: {
      bundleIds: ["com.jetbrains.intellij", "com.jetbrains.intellij.ce"],
      appNames: ["IntelliJ IDEA", "IntelliJ IDEA CE"],
    },
    linux: {
      executables: ["idea", "idea.sh"],
      desktopIds: ["jetbrains-idea.desktop", "jetbrains-idea-ce.desktop"],
      desktopIdPrefixes: ["jetbrains-idea"],
      flatpakIds: ["com.jetbrains.IntelliJ-IDEA-Ultimate", "com.jetbrains.IntelliJ-IDEA-Community"],
    },
  },
  {
    id: "datagrip",
    name: "DataGrip",
    kind: "editor",
    icon: "datagrip",
    supportedFileKinds: ["text"],
    windows: {
      executables: ["datagrip64.exe", "datagrip.exe"],
      uninstallNames: ["DataGrip"],
      toolbox: true,
    },
    macos: {
      bundleIds: ["com.jetbrains.datagrip"],
      appNames: ["DataGrip"],
    },
    linux: {
      executables: ["datagrip", "datagrip.sh"],
      desktopIds: ["jetbrains-datagrip.desktop"],
      desktopIdPrefixes: ["jetbrains-datagrip"],
      flatpakIds: ["com.jetbrains.DataGrip"],
    },
  },
  {
    id: "pycharm",
    name: "PyCharm",
    kind: "editor",
    icon: "pycharm",
    supportedFileKinds: ["text"],
    windows: {
      executables: ["pycharm64.exe", "pycharm.exe"],
      uninstallNames: ["PyCharm"],
      toolbox: true,
    },
    macos: {
      bundleIds: ["com.jetbrains.pycharm", "com.jetbrains.pycharm.ce"],
      appNames: ["PyCharm", "PyCharm CE"],
    },
    linux: {
      executables: ["pycharm", "pycharm.sh"],
      desktopIds: ["jetbrains-pycharm.desktop", "jetbrains-pycharm-ce.desktop"],
      desktopIdPrefixes: ["jetbrains-pycharm"],
      flatpakIds: ["com.jetbrains.PyCharm-Professional", "com.jetbrains.PyCharm-Community"],
    },
  },
  {
    id: "webstorm",
    name: "WebStorm",
    kind: "editor",
    icon: "webstorm",
    supportedFileKinds: ["text"],
    windows: {
      executables: ["webstorm64.exe", "webstorm.exe"],
      uninstallNames: ["WebStorm"],
      toolbox: true,
    },
    macos: {
      bundleIds: ["com.jetbrains.WebStorm"],
      appNames: ["WebStorm"],
    },
    linux: {
      executables: ["webstorm", "webstorm.sh"],
      desktopIds: ["jetbrains-webstorm.desktop"],
      desktopIdPrefixes: ["jetbrains-webstorm"],
      flatpakIds: ["com.jetbrains.WebStorm"],
    },
  },
  {
    id: "mpv",
    name: "mpv Media Player",
    kind: "media-player",
    icon: "mpv",
    supportedFileKinds: ["audio", "video"],
    windows: {
      executables: ["mpv.exe", "mpv.com"],
      uninstallNames: ["mpv"],
      knownPaths: ["%ProgramFiles%\\mpv\\mpv.exe", "%LOCALAPPDATA%\\Programs\\mpv\\mpv.exe"],
    },
    macos: {
      appNames: ["mpv"],
    },
    linux: {
      executables: ["mpv"],
      desktopIds: ["mpv.desktop", "io.mpv.Mpv.desktop"],
      flatpakIds: ["io.mpv.Mpv"],
    },
  },
  {
    id: "vlc",
    name: "VLC media player",
    kind: "media-player",
    icon: "vlc",
    supportedFileKinds: ["audio", "video"],
    windows: {
      executables: ["vlc.exe"],
      uninstallNames: ["VLC media player"],
      knownPaths: [
        "%ProgramFiles%\\VideoLAN\\VLC\\vlc.exe",
        "%ProgramFiles(x86)%\\VideoLAN\\VLC\\vlc.exe",
      ],
    },
    macos: {
      appNames: ["VLC"],
    },
    linux: {
      executables: ["vlc"],
      desktopIds: ["vlc.desktop", "org.videolan.VLC.desktop"],
      flatpakIds: ["org.videolan.VLC"],
    },
  },
  {
    id: "chrome",
    name: "Google Chrome",
    kind: "browser",
    supportedFileKinds: ["html", "pdf"],
    windows: {
      executables: ["chrome.exe"],
      appPaths: ["chrome.exe"],
      knownPaths: [
        "%ProgramFiles%\\Google\\Chrome\\Application\\chrome.exe",
        "%ProgramFiles(x86)%\\Google\\Chrome\\Application\\chrome.exe",
        "%LOCALAPPDATA%\\Google\\Chrome\\Application\\chrome.exe",
      ],
    },
    macos: { bundleIds: ["com.google.Chrome"], appNames: ["Google Chrome"] },
    linux: {
      executables: ["google-chrome", "google-chrome-stable"],
      desktopIds: ["google-chrome.desktop", "com.google.Chrome.desktop"],
      flatpakIds: ["com.google.Chrome"],
    },
  },
  {
    id: "edge",
    name: "Microsoft Edge",
    kind: "browser",
    supportedFileKinds: ["html", "pdf"],
    windows: {
      executables: ["msedge.exe"],
      appPaths: ["msedge.exe"],
      knownPaths: [
        "%ProgramFiles%\\Microsoft\\Edge\\Application\\msedge.exe",
        "%ProgramFiles(x86)%\\Microsoft\\Edge\\Application\\msedge.exe",
        "%LOCALAPPDATA%\\Microsoft\\Edge\\Application\\msedge.exe",
      ],
    },
    macos: { bundleIds: ["com.microsoft.edgemac"], appNames: ["Microsoft Edge"] },
    linux: {
      executables: ["microsoft-edge", "microsoft-edge-stable"],
      desktopIds: ["microsoft-edge.desktop", "com.microsoft.Edge.desktop"],
      flatpakIds: ["com.microsoft.Edge"],
    },
  },
  {
    id: "firefox",
    name: "Firefox",
    kind: "browser",
    supportedFileKinds: ["html", "pdf"],
    windows: {
      executables: ["firefox.exe"],
      appPaths: ["firefox.exe"],
      knownPaths: [
        "%ProgramFiles%\\Mozilla Firefox\\firefox.exe",
        "%ProgramFiles(x86)%\\Mozilla Firefox\\firefox.exe",
      ],
    },
    macos: { bundleIds: ["org.mozilla.firefox"], appNames: ["Firefox"] },
    linux: {
      executables: ["firefox", "firefox-esr"],
      desktopIds: [
        "firefox.desktop",
        "firefox-esr.desktop",
        "org.mozilla.firefox.desktop",
        "firefox_firefox.desktop",
      ],
      flatpakIds: ["org.mozilla.firefox"],
    },
  },
  {
    id: "chromium",
    name: "Chromium",
    kind: "browser",
    supportedFileKinds: ["html", "pdf"],
    linux: {
      executables: ["chromium", "chromium-browser"],
      desktopIds: [
        "chromium.desktop",
        "chromium-browser.desktop",
        "org.chromium.Chromium.desktop",
        "chromium_chromium.desktop",
      ],
      flatpakIds: ["org.chromium.Chromium"],
    },
  },
  {
    id: "safari",
    name: "Safari",
    kind: "browser",
    supportedFileKinds: ["html", "pdf"],
    macos: { bundleIds: ["com.apple.Safari"], appNames: ["Safari"] },
  },
  {
    id: "acrobat",
    name: "Adobe Acrobat",
    kind: "pdf-reader",
    supportedFileKinds: ["pdf"],
    windows: {
      executables: ["Acrobat.exe", "AcroRd32.exe"],
      uninstallNames: ["Adobe Acrobat", "Adobe Reader"],
    },
    macos: {
      bundleIds: ["com.adobe.Acrobat.Pro", "com.adobe.Reader"],
      appNames: ["Adobe Acrobat", "Adobe Acrobat Reader"],
    },
  },
  {
    id: "sumatra-pdf",
    name: "SumatraPDF",
    kind: "pdf-reader",
    supportedFileKinds: ["pdf"],
    windows: {
      executables: ["SumatraPDF.exe"],
      uninstallNames: ["SumatraPDF"],
      knownPaths: [
        "%LOCALAPPDATA%\\SumatraPDF\\SumatraPDF.exe",
        "%ProgramFiles%\\SumatraPDF\\SumatraPDF.exe",
      ],
    },
  },
  {
    id: "preview",
    name: "Preview",
    kind: "pdf-reader",
    supportedFileKinds: ["pdf", "image"],
    macos: {
      bundleIds: ["com.apple.Preview"],
      appNames: ["Preview"],
      knownPaths: ["/System/Applications/Preview.app"],
    },
  },
  {
    id: "okular",
    name: "Okular",
    kind: "pdf-reader",
    supportedFileKinds: ["pdf"],
    linux: {
      executables: ["okular"],
      desktopIds: ["org.kde.okular.desktop", "okularApplication_pdf.desktop"],
      flatpakIds: ["org.kde.okular"],
    },
  },
  {
    id: "gimp",
    name: "GIMP",
    kind: "image-editor",
    supportedFileKinds: ["image"],
    windows: {
      executables: ["gimp.exe", "gimp-3.exe", "gimp-2.10.exe"],
      uninstallNames: ["GIMP"],
    },
    macos: { appNames: ["GIMP", "GIMP-3.0", "GIMP-2.10"] },
    linux: {
      executables: ["gimp", "gimp-3.0"],
      desktopIds: ["gimp.desktop", "org.gimp.GIMP.desktop"],
      flatpakIds: ["org.gimp.GIMP"],
    },
  },
  {
    id: "inkscape",
    name: "Inkscape",
    kind: "image-editor",
    supportedFileKinds: ["image"],
    supportedFileExtensions: ["svg", "svgz"],
    windows: { executables: ["inkscape.exe"], uninstallNames: ["Inkscape"] },
    macos: { appNames: ["Inkscape"] },
    linux: {
      executables: ["inkscape"],
      desktopIds: ["org.inkscape.Inkscape.desktop", "inkscape.desktop"],
      flatpakIds: ["org.inkscape.Inkscape"],
    },
  },
  {
    id: "word",
    name: "Microsoft Word",
    kind: "office",
    supportedFileKinds: ["document"],
    supportedFileExtensions: ["doc", "docx", "docm", "dot", "dotx", "dotm", "odt", "rtf"],
    windows: { executables: ["WINWORD.EXE"] },
    macos: { bundleIds: ["com.microsoft.Word"], appNames: ["Microsoft Word"] },
  },
  {
    id: "excel",
    name: "Microsoft Excel",
    kind: "office",
    supportedFileKinds: ["document", "text"],
    supportedFileExtensions: [
      "xls",
      "xlsx",
      "xlsm",
      "xlsb",
      "xlt",
      "xltx",
      "xltm",
      "xla",
      "xlam",
      "ods",
      "csv",
      "tsv",
    ],
    windows: { executables: ["EXCEL.EXE"] },
    macos: { bundleIds: ["com.microsoft.Excel"], appNames: ["Microsoft Excel"] },
  },
  {
    id: "powerpoint",
    name: "Microsoft PowerPoint",
    kind: "office",
    supportedFileKinds: ["document"],
    supportedFileExtensions: [
      "ppt",
      "pptx",
      "pptm",
      "pot",
      "potx",
      "potm",
      "pps",
      "ppsx",
      "ppsm",
      "odp",
    ],
    windows: { executables: ["POWERPNT.EXE"] },
    macos: { bundleIds: ["com.microsoft.Powerpoint"], appNames: ["Microsoft PowerPoint"] },
  },
  {
    id: "libreoffice",
    name: "LibreOffice",
    kind: "office",
    supportedFileKinds: ["document", "text"],
    supportedFileExtensions: [
      "doc",
      "docx",
      "docm",
      "dot",
      "dotx",
      "dotm",
      "odt",
      "rtf",
      "xls",
      "xlsx",
      "xlsm",
      "xlsb",
      "xlt",
      "xltx",
      "xltm",
      "ods",
      "fods",
      "csv",
      "tsv",
      "ppt",
      "pptx",
      "pptm",
      "pot",
      "potx",
      "potm",
      "pps",
      "ppsx",
      "ppsm",
      "odp",
    ],
    windows: {
      executables: ["soffice.exe"],
      knownPaths: [
        "%ProgramFiles%\\LibreOffice\\program\\soffice.exe",
        "%ProgramFiles(x86)%\\LibreOffice\\program\\soffice.exe",
      ],
    },
    macos: { appNames: ["LibreOffice"] },
    linux: {
      executables: ["libreoffice", "soffice"],
      desktopIds: ["libreoffice-startcenter.desktop", "org.libreoffice.LibreOffice.desktop"],
      flatpakIds: ["org.libreoffice.LibreOffice"],
    },
  },
  {
    id: "onlyoffice",
    name: "ONLYOFFICE",
    kind: "office",
    supportedFileKinds: ["document", "text", "pdf"],
    supportedFileExtensions: [
      "doc",
      "docx",
      "docm",
      "dotx",
      "odt",
      "rtf",
      "xls",
      "xlsx",
      "xlsm",
      "xltx",
      "ods",
      "csv",
      "ppt",
      "pptx",
      "pptm",
      "potx",
      "ppsx",
      "odp",
      "pdf",
    ],
    windows: {
      executables: ["DesktopEditors.exe"],
      knownPaths: ["%ProgramFiles%\\ONLYOFFICE\\DesktopEditors\\DesktopEditors.exe"],
    },
    macos: { appNames: ["ONLYOFFICE"] },
    linux: {
      executables: ["desktopeditors", "onlyoffice-desktopeditors"],
      desktopIds: ["onlyoffice-desktopeditors.desktop", "org.onlyoffice.desktopeditors.desktop"],
      flatpakIds: ["org.onlyoffice.desktopeditors"],
    },
  },
  {
    id: "terminal",
    name: "Terminal",
    kind: "terminal",
    icon: "terminal",
    supportedFileKinds: [],
    targetMode: "directory",
    windows: {
      executables: ["wt.exe", "wt", "pwsh.exe", "powershell.exe", "cmd.exe"],
      appPaths: ["wt.exe"],
    },
    macos: {
      bundleIds: ["com.apple.Terminal"],
      appNames: ["Terminal"],
      knownPaths: ["/System/Applications/Utilities/Terminal.app"],
    },
    linux: {
      executables: ["ghostty", "wezterm", "kitty", "alacritty", "gnome-terminal", "konsole"],
    },
  },
];

export const FILE_MANAGER_APP = {
  id: "file-manager",
  name: "File Manager",
  kind: "file-manager",
  icon: "file-manager",
  supportedFileKinds: [],
  targetMode: "directory",
} satisfies LocalAppDefinition;
